### ISSUE TITLE
ImportError: No module named mesh.mesh

### ISSUE THREAD

**Issue by daydreamer2023** [thmoa/octopus#1]
Hi,  thank you for releasing the code for the paper @thmoa . I've cloned your code successfully on my ubuntu server. But when I run the **infer_single.py**, it shows an **ImportError: No module named mesh.mesh**. 
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "./infer_single.py", line 88, in <module>
    main(args.weights, args.name, args.segm_dir, args.pose_dir, args.out_dir, args.opt_steps_pose, args.opt_steps_shape)
  File "./infer_single.py", line 17, in main
    model = Octopus(num=len(segm_files))
  File "/home/***/***/octopus/model/octopus.py", line 169, in __init__
    sampling = pkl.load(f)
ImportError: No module named mesh.mesh
```

**Comment by thmoa** [comment]
strange...
could you please try installing https://github.com/MPI-IS/mesh?

**Comment by thmoa** [comment]
1a1938a should fix this

**Comment by daydreamer2023** [comment]
thank you very much !!!
