### ISSUE TITLE
keras report layer parameters number mismatch

### ISSUE THREAD

**Issue by meetwhom** [thmoa/octopus#12]
With all requirements met, I successfully setup the Octopus in Ubuntu Docker.
Dirt is ok
numpy is ok
scipy is ok
tensorflow-gpu is ok
keras is ok
(all components keep minimal version requirement)
But run_demo.sh report the following error:

root@28146d26637a:/home/thmoa/octopus# ./run_demo.sh 
Using TensorFlow backend.
2019-07-22 12:23:48.700476: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-22 12:23:48.701614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:05:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2019-07-22 12:23:48.701679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-07-22 12:23:49.266255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-22 12:23:49.266328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-07-22 12:23:49.266348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-07-22 12:23:49.266983: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10420 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "infer_single.py", line 89, in <module>
    main(args.weights, args.name, args.segm_dir, args.pose_dir, args.out_dir, args.opt_steps_pose, args.opt_steps_shape)
  File "infer_single.py", line 21, in main
    model = Octopus(num=len(segm_files))
  File "/home/thmoa/octopus/model/octopus.py", line 197, in __init__
    smpls = [NameLayer('smpl_{}'.format(i))(smpl([p, self.betas, t, self.offsets])) for i, (p, t) in enumerate(zip(self.poses, self.ts))]
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 460, in __call__
    output = self.call(inputs, **kwargs)
TypeError: call() takes exactly 5 arguments (2 given)

Is there any hint that I missed for the version?

**Comment by thmoa** [comment]
Did you use the Keras version as in requirements.txt? Try Keras 2.2.X.

**Comment by alakhag** [comment]
I am using Keras 2.2.4. I am till getting the same error.
