### ISSUE TITLE
Current Tensorflow is not compatible with octopus source

### ISSUE THREAD

**Issue by JamesDevGuru** [thmoa/octopus#15]
Hi,
I use :
Ubuntu 18.04.3 LTS
Python 2.7.15+
cuda_10.0
libcudnn7_7.6.2.24-1+cuda10.0_amd64
For last installation but again couldn't run!

But got error.
Do you provide tested configuration because my problem how i can make compatible tensorflow with Dirt and with this code! could you provide test configuration?
I tested many times on Ubuntu 16.4 and two version of Cuda and now on Ubuntu  18.4 and Cuda 10.0 because of Tensorflow 2.7 

Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0820 20:38:20.909133 140312402794304 deprecation_wrapper.py:119] From infer_single.py:19: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0820 20:38:20.909305 140312402794304 deprecation_wrapper.py:119] From infer_single.py:19: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0820 20:38:20.909396 140312402794304 deprecation_wrapper.py:119] From infer_single.py:19: The name tf.GPUOptions is deprecated. Please use tf.compat.v1.GPUOptions instead.

2019-08-20 20:38:20.914915: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-08-20 20:38:21.030470: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-20 20:38:21.031025: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5619f8538d30 executing computations on platform CUDA. Devices:
2019-08-20 20:38:21.031051: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080, Compute Capability 6.1
2019-08-20 20:38:21.052203: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3411290000 Hz
2019-08-20 20:38:21.052807: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5619f97f7650 executing computations on platform Host. Devices:
2019-08-20 20:38:21.052840: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-20 20:38:21.052988: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-20 20:38:21.053602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
2019-08-20 20:38:21.053939: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-20 20:38:21.055101: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-20 20:38:21.056089: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-20 20:38:21.056417: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-20 20:38:21.057829: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-20 20:38:21.058938: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-20 20:38:21.062348: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-20 20:38:21.062515: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-20 20:38:21.063226: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-20 20:38:21.063829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-20 20:38:21.063948: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-20 20:38:21.065663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-20 20:38:21.065683: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-20 20:38:21.065694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-20 20:38:21.065980: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-20 20:38:21.066705: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-20 20:38:21.067362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7327 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
W0820 20:38:21.068140 140312402794304 deprecation_wrapper.py:119] From /home/admin/VFS/venv/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0820 20:38:21.082931 140312402794304 deprecation.py:323] From /home/admin/VFS/octopus/smpl/batch_lbs.py:83: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Traceback (most recent call last):
  File "infer_single.py", line 89, in <module>
    main(args.weights, args.name, args.segm_dir, args.pose_dir, args.out_dir, args.opt_steps_pose, args.opt_steps_shape)
  File "infer_single.py", line 21, in main
    model = Octopus(num=len(segm_files))
  File "/home/admin/VFS/octopus/model/octopus.py", line 80, in __init__
    pose = tf.reshape(batch_rodrigues(pose_raw.reshape(-1, 3).astype(np.float32)), (-1, ))
  File "/home/admin/VFS/octopus/smpl/batch_lbs.py", line 93, in batch_rodrigues
    r, batch_size=batch_size)
  File "/home/admin/VFS/octopus/smpl/batch_lbs.py", line 51, in batch_skew
    with tf.name_scope("batch_skew", [vec]):
  File "/home/admin/VFS/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 6450, in __init__
    "pass this into the `values` kwarg." % type(default_name))
TypeError: `default_name` type (<type 'list'>) is not a string type. You likely meant to pass this into the `values` kwarg.

**Comment by thmoa** [comment]
Please use the configuration from `requirements.txt` and feel free to submit a PR. Thanks.

**Comment by JamesDevGuru** [comment]
Thank you  for in detail response 
I run below command and attached result all  requirements installed.  
pip install -r requirements.txt 
Just i need could your recommendation about OS,..... Witch OS or platform you tested this project? 

(venv) admin@adminlab:~/VFS/octopus$ pip install -r requirements.txt 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: scipy>=1.0.0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (1.2.2)
Requirement already satisfied: numpy>=1.16 in /home/admin/VFS/venv/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (1.16.4)
Requirement already satisfied: Keras>=2.2.0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (2.2.4)
Requirement already satisfied: tensorflow_gpu>=1.11.0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: dirt in /home/admin/VFS/dirt (from -r requirements.txt (line 5)) (0.3.0)
Requirement already satisfied: keras-applications>=1.0.6 in /home/admin/VFS/venv/lib/python2.7/site-packages (from Keras>=2.2.0->-r requirements.txt (line 3)) (1.0.8)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /home/admin/VFS/venv/lib/python2.7/site-packages (from Keras>=2.2.0->-r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: h5py in /home/admin/VFS/venv/lib/python2.7/site-packages (from Keras>=2.2.0->-r requirements.txt (line 3)) (2.9.0)
Requirement already satisfied: pyyaml in /home/admin/VFS/venv/lib/python2.7/site-packages (from Keras>=2.2.0->-r requirements.txt (line 3)) (5.1.2)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python2.7/dist-packages (from Keras>=2.2.0->-r requirements.txt (line 3)) (1.11.0)
Requirement already satisfied: grpcio>=1.8.6 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (1.23.0)
Requirement already satisfied: mock>=2.0.0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (3.0.5)
Requirement already satisfied: tensorboard<1.15.0,>=1.14.0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: wrapt>=1.11.1 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (1.11.2)
Requirement already satisfied: protobuf>=3.6.1 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (3.9.1)
Requirement already satisfied: gast>=0.2.0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (0.2.2)
Requirement already satisfied: wheel in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (0.33.6)
Requirement already satisfied: termcolor>=1.1.0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: absl-py>=0.7.0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (0.7.1)
Requirement already satisfied: tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: google-pasta>=0.1.6 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (0.1.7)
Requirement already satisfied: backports.weakref>=1.0rc1 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (1.0.post1)
Requirement already satisfied: enum34>=1.1.6 in /usr/lib/python2.7/dist-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (1.1.6)
Requirement already satisfied: astor>=0.6.0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (0.8.0)
Requirement already satisfied: futures>=2.2.0; python_version < "3.2" in /home/admin/VFS/venv/lib/python2.7/site-packages (from grpcio>=1.8.6->tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (3.3.0)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /home/admin/VFS/venv/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (1.0.2)
Requirement already satisfied: setuptools>=41.0.0 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (41.1.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (0.15.5)
Requirement already satisfied: markdown>=2.6.8 in /home/admin/VFS/venv/lib/python2.7/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow_gpu>=1.11.0->-r requirements.txt (line 4)) (3.1.1)

**Comment by VisionaryMind** [comment]
As of January, 2022, this repository is still broken. No versions of Tensorflow + Keras above 1.11 will run properly. Consistent errors are seen, depending on what versions are chosen together. Multiple times, users here have asked which TF + Keras configuration is required, stating that the _requirements.txt_ is not explicit enough and / or incorrect. It's unfortunate that others cannot use this very useful project because of an inability of the project owners to communicate dependencies properly. 

This code is not running on any of the TF + Keras combinations tried (and I have tried them all from 1.13 all the way up to 2.7 TF). We need to know, specifically, which ones you used to write the code. Currently, I am testing with TF-GPU 1.13.1 and Keras 2.2.4, and the following error is seen:

`AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'`

If I upgrade to TF-GPU 2.7.0 and Keras 2.7.0, then we have the problem with the hd5-format changing in the new(er) Keras versions. That manifests as:

```
 f'Shape mismatch in layer #{k} (named {layer.name}) for weight '
ValueError: Shape mismatch in layer #5 (named conv2d_1) for weight conv2d_1/kernel:0. Weight expects shape (3, 3, 8, 16). 
Received saved weight with shape (8, 3, 3, 3)
```

But, as I have mentioned above, going backward on that version in order to have it work with your code is also hit or miss (and mostly miss). I and many other people here have not found a workaround. It's either this project or Neuralbody --- and the prospect of training a model for days just to get a poorly shaped mesh is not very appealing. This project looks to be more efficient (and faster).
