### ISSUE TITLE
SVD gradient is not implemented for compute_uv=True and full_matrices=False

### ISSUE THREAD

**Issue by ronixy** [thmoa/octopus#2]
hi，I got this error when run run_demo.sh, does it require specific tensorflow version ?  I'm using tensorflow 1.5.0 and keras 2.1.4, os is ubuntu 16.04. 

Optimizing for pose...
  0%|          | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "infer_single.py", line 85, in <module>
    main(args.weights, args.name, args.segm_dir, args.pose_dir, args.out_dir, args.opt_steps_pose, args.opt_steps_shape)
  File "infer_single.py", line 34, in main
    model.opt_pose(segmentations, joints_2d, opt_steps=opt_pose_steps)
  File "/home/bodymesh/octopus-master/model/octopus.py", line 290, in opt_pose
    callbacks=[LambdaCallback(on_batch_end=lambda e, l: pbar.update(1))]
  File "/home/bodymesh/octopus-master/test/local/lib/python2.7/site-packages/keras/engine/training.py", line 1689, in fit
    self._make_train_function()
  File "/home/bodymesh/octopus-master/test/local/lib/python2.7/site-packages/keras/engine/training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "/home/bodymesh/octopus-master/test/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/bodymesh/octopus-master/test/local/lib/python2.7/site-packages/keras/optimizers.py", line 440, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/bodymesh/octopus-master/test/local/lib/python2.7/site-packages/keras/optimizers.py", line 78, in get_gradients
    grads = K.gradients(loss, params)
  File "/home/bodymesh/octopus-master/test/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2512, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "/home/bodymesh/octopus-master/test/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 609, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/bodymesh/octopus-master/test/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 375, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/bodymesh/octopus-master/test/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 609, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/bodymesh/octopus-master/test/local/lib/python2.7/site-packages/tensorflow/python/ops/linalg_grad.py", line 275, in _SvdGrad
    "SVD gradient is not implemented for compute_uv=True and "
NotImplementedError: SVD gradient is not implemented for compute_uv=True and full_matrices=False.

**Comment by thmoa** [comment]
Please check requirements.txt.
