### ISSUE TITLE
It seems the requirements are too strict 

### ISSUE THREAD

**Issue by meetwhom** [thmoa/octopus#20]
My basic environment:
tensorflow-gpu = 1.11.0
keras = 2.2.4 (which is slightly above 2.2.0)

And dirt is ok, compiled from source.
I am using conda and python version is 2.7.16.

While running the test script file run_demo.sh, it reports the following error:

------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "infer_single.py", line 89, in <module>
    main(args.weights, args.name, args.segm_dir, args.pose_dir, args.out_dir, args.opt_steps_pose, args.opt_steps_shape)
  File "infer_single.py", line 21, in main
    model = Octopus(num=len(segm_files))
  File "/home/sdb/ab/thmoa/octopus/model/octopus.py", line 198, in __init__
    enumerate(zip(self.poses, self.ts))]
  File "/home/sam/miniconda3/envs/octopus/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
TypeError: call() takes exactly 5 arguments (2 given)
----------------------------------------------------------------------------------------------

I guess maybe the keras version difference cause this?

**Comment by thmoa** [comment]
You are welcome to submit a PR!

**Comment by quyanqiu** [comment]
@meetwhom not really ,keras 2.2.5 with tensorflow 1.13.1 works fine

**Comment by OOF-dura** [comment]
> @meetwhom not really ,keras 2.2.5 with tensorflow 1.13.1 works fine

Are you using py2.7?

**Comment by OOF-dura** [comment]
> @meetwhom not really ,keras 2.2.5 with tensorflow 1.13.1 works fine

hi @quyanqiu @thmoa I am using py2.7 with
```
tensorboard          1.13.1      
tensorflow-estimator 1.13.0      
tensorflow-gpu       1.13.1 
Keras                2.2.5       
Keras-Applications   1.0.8       
Keras-Preprocessing  1.1.2    
...
```
I got the following error:
```
Traceback (most recent call last):
  File "infer_single.py", line 89, in <module>
    main(args.weights, args.name, args.segm_dir, args.pose_dir, args.out_dir, args.opt_steps_pose, args.opt_steps_shape)
  File "infer_single.py", line 21, in main
    model = Octopus(num=len(segm_files))
  File "/home/frank/PycharmProjects/octopus/model/octopus.py", line 207, in __init__
    [self.vertices_tposed, vertices_naked])
  File "/home/frank/anaconda3/envs/octopus27/lib/python2.7/site-packages/keras/engine/base_layer.py", line 451, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/frank/anaconda3/envs/octopus27/lib/python2.7/site-packages/keras/layers/core.py", line 716, in call
    return self.function(inputs, **arguments)
TypeError: <lambda>() takes exactly 2 arguments (1 given)

````
