### ISSUE TITLE
While running the " run_demo.sh" script, I get the following error. Is it related to the tensorflow version? I am using 1.12.0. cuda 9.0 cudnn 7.14

### ISSUE THREAD

**Issue by YaolinHou** [thmoa/octopus#7]
`Optimizing for pose...
100%|██████████| 5/5 [00:20<00:00,  4.97s/it]
Optimizing for shape...
  0%|          | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "infer_single.py", line 89, in <module>
    main(args.weights, args.name, args.segm_dir, args.pose_dir, args.out_dir, args.opt_steps_pose, args.opt_steps_shape)
  File "infer_single.py", line 42, in main
    model.opt_shape(segmentations, joints_2d, face_2d, opt_steps=opt_shape_steps)
  File "/home/yaolin/Documents/octopus/model/octopus.py", line 329, in opt_shape
    callbacks=[LambdaCallback(on_batch_begin=lambda e, l: pbar.update(1))]
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1010, in fit
    self._make_train_function()
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 509, in _make_train_function
    loss=self.total_loss)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/optimizers.py", line 475, in get_updates
    grads = self.get_gradients(loss, params)
  File "/usr/local/lib/python2.7/dist-packages/keras/optimizers.py", line 89, in get_gradients
    grads = K.gradients(loss, params)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2757, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 630, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 848, in _GradientsHelper
    (op.name, i, t_in.shape, in_grad.shape))
ValueError: Incompatible shapes between op input and calculated input gradient.  Forward operation: render_layer_7/render_batch.  Input index: 0. Original input shape: (?, 1080, 1080, 1).  Calculated input gradient shape: (?, 32766, 8, 0)
`

**Comment by thmoa** [comment]
#3
